server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/school?useUnicode=true&characterEncoding=utf8
    username: ygh
    password: ygh
  jpa:
    hibernate:
       ddl-auto: create
#       ddl-auto: update
       show-sql: true
  mvc:
   view:
     suffix: .ftl